apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    helm.sh/chart: actions-cache-server-0.0.0
    app.kubernetes.io/name: actions-cache-server
    app.kubernetes.io/version: 0.0.0
    app.kubernetes.io/managed-by: Helm
  name: actions-cache-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: actions-cache-server
  revisionHistoryLimit: 10
  minReadySeconds: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: actions-cache-server
    spec:
      containers:
        - name: server
          image: TODO
          imagePullPolicy: IfNotPresent
          env:
            - name: LISTEN_ADDR
              value: 0.0.0.0:80
            - name: LOG_LEVEL
              value: info
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      nodeSelector:
        kubernetes.io/os: linux
