---
name: 'CI'

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  # TODO tests

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - golangci
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/terrycain/actions-cache-server:${{ steps.get_version.outputs.version }}
