---
name: 'Tests'

on:
  push:
    branches:
      - "*"

jobs:
  golangci:
    name: golangci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
  unittests:
    name: unit-tests
    runs-on: ubuntu-latest
    services:
      localstack:
        image: docker.io/localstack/localstack:latest
        env:
          SERVICES: s3
        ports:
          - 4566:4566

      postgres:
        image: docker.io/library/postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: actionscache
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Restore Go cache
        uses: actions/cache@v1
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Setup gotestsum
        run: go install gotest.tools/gotestsum@v1.7.0

      - name: Run Tests
        env:
          # Localstack S3
          STORAGE_S3: http://localhost:${{ job.services.localstack.ports[4566] }}
          DB_POSTGRES: postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/actionscache?sslmode=disable
        run: gotestsum --junitfile junit.xml --format testname
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: junit.xml

  helm:
    name: helm-validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Helm chart
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.19.11
          helm: 2.17.0
          helmv3: 3.6.0
          command: |
            helmv3 template ./charts/actions-cache-server | kubeval --strict --kubernetes-version 1.19.11 --schema-location https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master
      - name: Validate kustomization
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.19.11
          command: |
            kustomize build ./kustomize | kubeval --strict --kubernetes-version 1.19.11 --schema-location https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master
            kustomize build ./kustomize | conftest test -p .github/policy -
