---
name: 'Tests'

on:
  push:
    branches:
      - "*"

jobs:
  golangci:
    name: golangci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
  unittests:
    name: unit-tests
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        env:
          SERVICES: s3
        ports:
          - 4566-4566
    steps:
      - uses: actions/checkout@v2
      - name: Restore Go cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Setup gotestsum
        run: go install gotest.tools/gotestsum@v1.7.0

      - name: Run Tests
        env:
          # Localstack S3
          STORAGE_S3: http://localhost:${{ job.services.localstack.ports[4566] }}
        run: gotestsum --junitfile junit.xml --format testname
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: junit.xml

  helm:
    name: helm-validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Helm chart
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.19.11
          helm: 2.17.0
          helmv3: 3.6.0
          command: |
            helmv3 template ./charts/actions-cache-server | kubeval --strict --kubernetes-version 1.19.11 --schema-location https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master
      - name: Validate kustomization
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.19.11
          command: |
            kustomize build ./kustomize | kubeval --strict --kubernetes-version 1.19.11 --schema-location https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master
            kustomize build ./kustomize | conftest test -p .github/policy -



  e2e:
    name: e2e
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        env:
          SERVICES: s3
        ports:
          - 4566-4566
    strategy:
      fail-fast: false
      matrix:
        storage:
          - s3
          - disk
        database:
          - sqlite
    steps:
      - uses: actions/checkout@v2
      - name: Restore Go cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Build
        run: |
          make build
      - name: Generate cache data
        run: |
          ./.github/ci-scripts/generate-data.sh

      - name: Run server
        env:
          LOCALSTACK: http://localhost:${{ job.services.localstack.ports[4566] }}
        run: |
          ./.github/ci-scripts/run-server.sh ${{matrix.storage}} ${{matrix.database}}

      - name: Test cache is still running
        run: |
          curl -vv http://127.0.0.1:8080/ping


      - name: Output log
        if: always()
        run: |
          cat log.txt
          truncate --size=0 log.txt

      - name: Clear cache
        run: |
          ./.github/ci-scripts/clear-data.sh
